//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hbxlsEntities : DbContext
    {
        public hbxlsEntities()
            : base("name=hbxlsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<wx_xx_d_offal> wx_xx_d_offal { get; set; }
        public virtual DbSet<wx_xx_d_repertory> wx_xx_d_repertory { get; set; }
        public virtual DbSet<wx_xx_d_sterilize> wx_xx_d_sterilize { get; set; }
        public virtual DbSet<wx_xx_government> wx_xx_government { get; set; }
        public virtual DbSet<wx_xx_shop> wx_xx_shop { get; set; }
        public virtual DbSet<wx_xx_user> wx_xx_user { get; set; }
    }
}
