//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_xx_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wx_xx_user()
        {
            this.wx_xx_d_offal = new HashSet<wx_xx_d_offal>();
            this.wx_xx_d_repertory = new HashSet<wx_xx_d_repertory>();
            this.wx_xx_d_sterilize = new HashSet<wx_xx_d_sterilize>();
        }
    
        public int Id { get; set; }
        public string open_id { get; set; }
        public string cnname { get; set; }
        public int wx_xx_shopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wx_xx_d_offal> wx_xx_d_offal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wx_xx_d_repertory> wx_xx_d_repertory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wx_xx_d_sterilize> wx_xx_d_sterilize { get; set; }
        public virtual wx_xx_shop wx_xx_shop { get; set; }
    }
}
