//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace web
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_xx_d_repertory
    {
        public int Id { get; set; }
        public string CargoName { get; set; }
        public string Type { get; set; }
        public double Quantity { get; set; }
        public string BatchNum { get; set; }
        public string Expiration_date { get; set; }
        public string Supplier { get; set; }
        public string Purchasing_Openid { get; set; }
        public string Acceptor_Openid { get; set; }
        public System.DateTime Date { get; set; }
        public int Shop_id { get; set; }
    }
}
